---
- name: Server setup
  hosts: all
  become: true

  tasks:
  - name: Gather package facts
    ansible.builtin.package_facts:
      manager: "auto"

  - name: Install Podman
    ansible.builtin.apt:
      name: podman
      state: present
      update_cache: true
    when: "'podman' not in ansible_facts.packages"
    
    tags: provision
  

- name: Nextcloud environment setup
  hosts: all

  tasks:
  - name: Create Network
    containers.podman.podman_network:
      name: nextcloud-net

  - name: Create Volumes
    containers.podman.podman_volume:
      state: present # state
      name: "{{ item }}"
    loop:
      - nextcloud-app
      - nextcloud-data
      - nextcloud-db
    
    tags: provision

- name: Nextcloud Database setup
  hosts: all

  tasks:
  - name: Deploy PostgreSQL
    containers.podman.podman_container:
      name: nextcloud-db
      image: docker.io/postgres:13.4-alpine
      state: started # state
      restart: true
      volume:
        - nextcloud-db:/var/lib/postgresql/data
      network:
        - nextcloud-net
      env:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"
    no_log: true

  - name: Pause for 1 minute untill database is ready
    ansible.builtin.pause:
      minutes: 1


- name: Nextcloud Setup
  hosts: all

  tasks:
  - name: Deploy nextcloud container
    containers.podman.podman_container:
      name: nextcloud
      image: docker.io/nextcloud
      state: started # state
      restart: true
      volume:
        - nextcloud-app:/var/www/html
        - nextcloud-data:/var/www/html/data
      network:
        - nextcloud-net
      ports:
        - 8080:80
      env:
        POSTGRES_HOST: "nextcloud-db"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"
        NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
        NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_trusted_domains }}"
      # recreate: true
    no_log: true
