---
- name: Server setup
  hosts: lab
  become: yes

  tasks:
  - name: Install Podman
    ansible.builtin.apt:
      name: podman
      state: latest
      update_cache: yes

- name: Nextcloud environment setup 
  hosts: lab

  tasks:
  - name: Create Network
    containers.podman.podman_network:
      name: nextcloud-net

  - name: Create Volumes
    containers.podman.podman_volume:
      name: "{{ item }}"
    loop:
      - nextcloud-app
      - nextcloud-data
      - nextcloud-db

- name: Nextcloud Database setup
  hosts: lab

  tasks:
  - name: Deploy PostgreSQL
    containers.podman.podman_container:
      name: nextcloud-db 
      image: docker.io/postgres:13.4-alpine
      state: started
      restart: yes
      volume:
        - nextcloud-db:/var/lib/postgresql/data
      network: 
        - nextcloud-net
      env:
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"
      recreate: true
    no_log: True


- name: Nextcloud Setup
  hosts: lab

  tasks:
  - name: Deploy nextcloud container
    containers.podman.podman_container:
      name: nextcloud
      image: docker.io/nextcloud
      state: started
      restart: yes
      volume:
        - nextcloud-app:/var/www/html
        - nextcloud-data:/var/www/html/data
      network: 
        - nextcloud-net
      ports:
        - 8085:80
      env:
        POSTGRES_HOST: "nextcloud-db"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        POSTGRES_DB: "{{ postgres_db }}"
        NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      recreate: true
    no_log: True
