---
- name: Prepare SSL Certs Renewal
  hosts: all
  gather_facts: false
  vars_files:
    - vars/vars.yml

  # handlers:
  #   - name: Reload haproxy
  #     service:
  #       name: haproxy
  #       state: reload
  #     listen: "reload haproxy"

  tasks:

    - name: Check if Letsencrypt folder exists
      stat:
        path: "{{ letsencrypt_dir }}"
      register: letsencrypt_folder

    - name: Destroy Letsencrypt folder
      file:
        path: "{{ letsencrypt_dir }}"
        state: absent
      when: letsencrypt_folder.stat.exists

    - name: "Create required directories in letsencrypt"
      file:
        path: "{{ letsencrypt_dir }}/{{ item }}"
        state: directory
        # owner: root
        # group: root
        mode: u=rwx,g=x,o=x
      with_items:
      - account
      - certs
      - csrs
      - keys

    - stat:
        path: "{{ letsencrypt_account_key }}"
      register: account_key

    - name: "Generate a Let's Encrypt account key"
      shell: "if [ ! -f {{ letsencrypt_account_key }} ]; then openssl genrsa 4096 | tee {{ letsencrypt_account_key }}; fi"
      when: account_key.stat.exists == False
      changed_when: false

    - stat: 
        path: "{{ letsencrypt_keys_dir }}/{{ item }}.key }}"
      register: private_key
      with_items: "{{ domain_names }}"

    - name:
      include_tasks: tasks/generate.yml
      loop: "{{ domain_names }}"
      loop_control:
        loop_var: item
        extended: yes
      when: private_key['results'][ansible_loop.index0]['stat']['exists'] == False

    - name: "Begin LetsEncrypt challenges"
      acme_certificate:
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        account_key_src: "{{ letsencrypt_account_key }}"
        account_email: "{{ acme_email }}"
        terms_agreed: yes
        challenge: "{{ acme_challenge_type }}"
        src: "{{ letsencrypt_csrs_dir }}/{{ item }}.csr"
        cert: "{{ letsencrypt_certs_dir }}/{{ item }}.crt"
        remaining_days: 60
        force: yes
      register: acme_challenge_data
      with_items: "{{ domain_names }}"
      retries: 3
      delay: 3
      until: acme_challenge_data is changed
      #ignore_errors: True


- name: Prepare the challenge
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/vars.yml
  
  tasks:

    - name: Copy challenge data in nginx webroot folder
      copy:
        dest: "{{ nginx_folder }}/{{ acme_challenge_data.results[0].challenge_data[item]['http-01']['resource'] }}"
        content: "{{ acme_challenge_data.results[0].challenge_data[item]['http-01']['resource_value'] }}"
      with_items: "{{ domain_names }}"
      when: acme_challenge_data is changed
      ignore_errors: True


- name: Validation
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/vars.yml

  tasks:

    - name: Validate challenge and retrieve certs
      acme_certificate:
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        account_key_src: "{{ letsencrypt_account_key }}"
        account_email: "{{ acme_email }}"
        terms_agreed: yes
        challenge: "{{ acme_challenge_type }}"
        src: "{{ letsencrypt_csrs_dir }}/{{ item }}.csr"
        cert: "{{ letsencrypt_certs_dir }}/{{ item }}.crt"
        fullchain: "{{ letsencrypt_certs_dir }}/{{ item }}-fullchain.crt"
        chain: "{{ letsencrypt_certs_dir }}/{{ item }}-intermediate.crt"
        remaining_days: 60
        force: yes
        data: "{{ acme_challenge_data.results[0] }}"
          #register: acme_challenge_data
      with_items: "{{ domain_names }}"
      when: acme_challenge_data is changed

# - name: Update nexcloud nginx configuration    

    